server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    jdbcUrl: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&useSSL=false


# PooledConnectionFactory  ConfigurationProperties
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.86.128:22122
  web-server-url: 192.168.86.128:80
